flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    # for posting new blog
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Your Post', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post


main = Blueprint('main', __name__)  # similar to app = Flask(__name__)


@main.route('/home')
@main.route('/')
def home():
    page = request.args.get('page', 1, type=int)  # getting the page. Default page is 1
    # posts = Post.query.all()  # kept it here to show how I did it earlier
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)  # to prevent grabbing and loading all the posts at once
    return render_template("home.html", posts=posts)


@main.route('/about')
def about():
    return render_template("about.html", title='about')

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm


posts = Blueprint('posts', __name__)  # similar to app = Flask(__name__)


@posts.route('/post/new', methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("New post created.", "success")
        return redirect(url_for("main.home"))
    return render_template("create_post.html", title='new post', form=form, legend='Create Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # forbidden route
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("The post has been updated.", "success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template("create_post.html", title='edit', form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)  # forbidden route
    db.session.delete(post)
    db.session.commit()
    flash("The post has been deleted.", "success")
    return redirect(url_for("main.home"))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)  # similar to app = Flask(__name__)


@users.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        # if user is already logged in
        return redirect(url_for("main.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        # hashing the password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')  # decode needed to get string hash
        # creating a new user
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        flash(f"Account created for {form.username.data}.", "success")
        return redirect(url_for("users.login"))
    return render_template('register.html', title='register', form=form)


@users.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        # if user is already logged in
        return redirect(url_for("main.home"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')  # returns none if next argument is not there
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash("Login unsuccessful. Please check username or password.", "danger")
    return render_template('login.html', title='login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route('/edit_profile', methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Account has been updated.", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=f'profile_pic/{current_user.image_file}')
    return render_template("account.html", title="edit profile", image_file=image_file, form=form)


@users.route('/<string:username>', methods=["GET", "POST"])
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template("user_posts.html", posts=posts, user=user, title=user.username)


@users.route('/reset_password', methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        # if user is already logged in
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash('If an account with this email address exists, an email has been sent with instructions to the specified email.', "info")
            return redirect(url_for("users.login"))
        else:
            flash('If an account with this email address exists, an email has been sent with instructions to the specified email.', "info")
            return redirect(url_for("users.login"))
    return render_template("reset_request.html", title="reset password", form=form)


@users.route('/reset_password/<token>', methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        # if user is already logged in
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash('The token is invalid or expired.', "warning")
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # hashing the password
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')  # decode needed to get string hash
        # creating a new user
        user.password = hashed_password
        db.session.commit()

        flash(f"Your password has been updated!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="reset password", form=form)

flaskblog/templates/about.html
{% extends "layouts.html" %}
    {% block content %}
        <h4>About</h4>
    {% endblock content %}

flaskblog/templates/account.html
{% extends "layouts.html" %}
    {% block content %}
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ image_file }}" alt="Profile Picture">
                <div class="media-body">
                    <h2 class="account-heading">{{ current_user.username }}</h2>
                    <p class="text-secondary">{{ current_user.email }}</p>
                </div>
            </div>
            <div class="content-section">
                <form method="POST" action="" enctype="multipart/form-data">
                    <!-- enctype for ecnoding the image -->
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Account Info</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
                            {% if form.username.errors %}
                                {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control form-control-lg") }}
                            {% endif %}
                        </div>
                        <div class="form-group mt-4">
                            {{ form.picture.label() }}
                            <br><br>
                            {{ form.picture(class="form-control-file") }}
                            {% if form.picture.errors %}
                                <br>
                                {% for error in form.picture.errors %}
                                    <span class="text-danger">{{ error }}</span><br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </fieldset>
                    <div class="form-group pt-3">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
            </div>
        </div>
    {% endblock content %}

flaskblog/templates/create_post.html
{% extends "layouts.html" %}
    {% block content %}
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">{{ legend }}</legend>
                    <div class="form-group">
                        {{ form.title.label(class="form-control-label") }}
                        {% if form.title.errors %}
                            {{ form.title(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.title(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.content.label(class="form-control-label") }}
                        {% if form.content.errors %}
                            {{ form.content(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.content(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group pt-3">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    {% endblock content %}

flaskblog/templates/home.html
{% extends "layouts.html" %}
    {% block content %}
        {% for post in posts.items %}
            <article class="content-section">
                <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
                <div class="media-body">
                    <div class="article-metadata">
                      <a class="article-metadata" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                      <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.content }}</p>
                </div>
            </article>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, right_current=2, left_current=1) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    {% endblock content %}

flaskblog/templates/layouts.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags for adding bootstrap-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        {% if title %}
            <title>Fake Blog- {{ title }}</title>
        {% else %}
            <title>Fake Blog</title>
        {% endif %}
    </head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Fake Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <!-- Navbar Right Side -->
                        <div class="navbar-nav ml-1" align='right'>
                            {% if current_user.is_authenticated %}
                                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.user_posts', username=current_user.username) }}">Account</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                            {% else %}
                                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Quick Links</h3>
                    <p class='text-muted'>
                        <ul class="list-group">
                            <li class="list-group-item list-group-item-light">
                                <a class="article-metadata" href="{{ url_for('users.account') }}">Edit profile</a>
                            </li>
                            <li class="list-group-item list-group-item-light">
                                <a class="article-metadata" href="{{ url_for('main.about') }}">About</a>
                            </li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

flaskblog/templates/login.html
{% extends "layouts.html" %}
    {% block content %}
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check pt-2">
                        {{ form.remember.label(class="form-check-label")}}
                        {{ form.remember(class="form-check-input")}}
                    </div>
                </fieldset>
                <div class="form-group pt-3">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
                <div class="pt-3">
                    <small class="text-muted">
                        <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
                    </small>
                </div>
            </form>
        </div>
        <div class="border-top pt-1">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
            </small>
        </div>
    {% endblock content %}

flaskblog/templates/post.html
{% extends "layouts.html" %}
    {% block content %}
        <article class="content-section">
            <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pic/' + post.author.image_file) }}">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="article-metadata" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
                    {% if post.author == current_user %}
                        <div>
                            <a class="btn btn-secondary btn-sm mt-2 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update Post</a>
                            <button type="button" class="btn btn-danger btn-sm mt-2 mb-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                        </div>
                    {% endif %}
                </div>
                <hr>
                <h2 class="article-title-show">{{ post.title }}</h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
        <!-- Modal -->
        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                        <button type="button" class="btn btn-sm" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                        <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                            <input type="submit" class="btn btn-danger" value="Delete">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endblock content %}

flaskblog/templates/register.html
{% extends "layouts.html" %}
    {% block content %}
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Join Today</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.confirm_password.label(class="form-control-label") }}
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group pt-3">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
        <div class="border-top pt-1">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Login</a>
            </small>
        </div>
    {% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layouts.html" %}
    {% block content %}
        <div class="content-section">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Reset Password</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group pt-3">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    {% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layouts.html" %}
    {% block content %}
        <div class="media">
            <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pic/' + user.image_file) }}" alt="Profile Picture">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        {% for post in posts.items %}
            <article class="content-section">
                <div class="media-body">
                    <div class="article-metadata">
                        <a class="article-metadata" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                        <small class="text-muted">{{ post.date_posted.strftime("%Y-%m-%d") }}</small>
                    </div>
                    <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                    <p class="article-content">{{ post.content }}</p>
                </div>
            </article>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, right_current=2, left_current=1) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', page=page_num, username=user.username) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', page=page_num, username=user.username) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    {% endblock content %}